---
title: "Untitled"
output: pdf_document
---

In Model 4, *african americans* remains highly significant and, as expected, negatively correlated with states’ basic assistance spending. On average, a state that experienced a 1% increase in the portion of its TANF caseload composed of African Americans spent .249% less on basic assistance in the following fiscal year. Such a finding corresponds to the conclusions of @gilensRaceCodingWhite1996, @fellowesPoliticsNewAmerican2004, and @sossSettingTermsRelief2001 and underlines the role that race continues to play in shaping TANF policy outcomes. In contrast, *hispanics* is neither significant nor in the hypothesized direction in the final model. The evolution of *hispanics* across the four models indicates that its significance in Models 1 and 2 was the spurious result of either omitted variable bias stemming from correlations with economic factors or national demographic changes controlled for by time fixed effects in Model 4. Regardless of the exact reason for its insignificance in the final model, *hispanics*’ positive and insignificant coefficient is not unprecedented. As mentioned above, @fellowesPoliticsNewAmerican2004 find significant inverse relationships between the percentage of Latinos receiving TANF benefits in a state and both the flexibility of work requirements and the strictness of TANF eligibility criteria. Similar to my own findings, the authors illustrate that the influence of Hispanic welfare recipients on TANF policy outcomes is not straightforward. Unlike in the case of African Americans, where there is clear evidence that negative perceptions significantly affect TANF and other social welfare policy outcomes, the share of a state's caseload composed of Hispanics seems to bear a more nuanced, undetermined influence on TANF spending. 

Turning to economic factors, Model 4 does not provide any evidence in support of my hypothesis that states with budget shortfalls will reduce basic assistance spending to cover costs. Likewise, the final model does not support my claim that states’ per capita personal incomes are negatively associated with basic assistance spending and only weakly implies that states’ unemployment rates positively correlate with basic assistance expenditures. The dramatic shifts in the magnitude and significance of *pcpi regional* and *unemployment* relative to Model 3 are a likely product of national changes in economic conditions. What appears in Model 3 as significant relationships between state-level economic variation and basic assistance spending variation are the spurious results of simultaneous aggregate movements in economic conditions and TANF spending, not potentially causal relationships at the state-level. 

Model 4 indicates that a state that experienced a 1% decline in its TANF caseload from the prior year spent, on average, .15% less on basic assistance in the following year. The increase in *caseload*’s magnitude as compared to Model 3 suggests that isolating the relationship between caseload change and basic assistance expenditures from the aggregate decreases in states’ TANF caseloads increases the direct correlation between caseload size and basic assistance spending. In other words, even when aggregate trends in caseload sizes are accounted for, states that experienced greater decreases in caseload sizes spent a lower share of their TANF block grants on basic assistance – a finding that both corresponds to my hypothesis that basic assistance spending is sensitive to caseload sizes and helps explain the observed variation within the overall trend of lower basic assistance spending. 

As discussed above, the influence of the work participation requirement on basic assistance spending is theoretically ambiguous. States can reduce the burden of the requirement by either increasing the number of employed recipients through greater basic assistance spending or decreasing the number of unemployed recipients, with the tangential effect of lower basic assistance expenditures. However, as illustrated in Model 4, the empirical relationship between the work participation requirement and basic assistance spending is clear: States that did not meet their work participation rate in the prior year spent, on average, 5.102% more on basic assistance in the following year. The highly significant coefficient rejects the hypothesis that there was a broad push among the states to remove unemployed recipients from their caseloads (and thereby create a smaller caseload with higher incomes) in response to not meeting the work participation rate requirement. 

Similar to *caseload* and *wpr*, the introduction of time fixed effects in Model 4 increases the magnitude of *liberalism*, suggesting that national changes in political ideology and aggregate changes in other state-level variables served as negative confounders in earlier models. As hypothesized, *liberalism* is positive and significant in Model 4, implying that more progressive state governments allocate larger shares of TANF funds to basic assistance. Such a finding corresponds to my hypothesis concerning progressivism and basic assistance spending as well as the well-established relationship between political ideology and social welfare spending more broadly. 

Finally, although masked in Table 1 for readability, the coefficients on the time fixed effects in Model 4 are presented below in Figure 5. The coefficients are all highly significant and of a large magnitude. Holding constant the eight state-level independent variables specified in Model 4, states spent, on average, 34.8% less on proportional basic assistance in FY 2013 than 1998. The coefficients underline the fact that although states did not decrease basic assistance spending in lock-step, they all participated in a national retrenchment of basic assistance spending. While understanding the national trend on its own, as a separate phenomenon from the role of state-level characteristics on TANF spending, is not taken up here, it certainly warrants future study. 